version: '3.2'
services:

#Media Player
  player.homeflix.kodi:
    image: homeflix/kodi
    build:
      context: player/kodi
    networks:
      - homeflix

#Torrent
  torrent.homeflix.transmission:
    image: homeflix/transmission
    build:
      context: torrent/transmission
    ports:
      - "8085:9091"
    networks:
      - homeflix

#Movies
  movies.homeflix.radarr:
    image: homeflix/radarr
    build:
      context: movies/radarr
    ports:
      - "8083:9091"
    networks:
      - homeflix

#Series
  series.homeflix.sonarr:
    image: homeflix/sonarr
    build:
      context: series/sonarr
    ports:
      - "8082:9091"
    networks:
      - homeflix

networks:
  homeflix:

volumes:
  homeflix-drive:
