version: '3.2'
services:

#Torrent
  series.homeflix.sonarr:
    container_name: series.homeflix.sonarr
    image: homeflix/sonarr
    build:
      context: .
    ports:
      - "8882:8989"
    networks:
      - homeflix

networks:
  homeflix:

volumes:
  homeflix-drive:
